### PR TITLE
Implement GSP-729 Redesign HTTP Signer

### PR DESCRIPTION
**Pull request by JinnyYi**
ref: https://github.com/beyondstorage/go-integration-test/pull/49#discussion_r692621774

### CODE REVIEW

**Comment by JinnyYi** [comment]
`PutObject` in chunked transfer encoding will get `411 Length Required` error. `req.ContentLength` can set the `Content-Length` header.

**Comment by Xuanwo** [comment]
Mostly LGTM, let's start ship this feature!

**Comment by Xuanwo** [comment]
Bravo!

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
Let's kick a new release, and let https://forum.beyondstorage.io/t/access-control-linode-s3-compatible-object-storage/184 know about it.

**Pull request merged**
